server:
  port: 8082


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/rating-service


  # Configuring Spring Data MongoDB                 # Enable Spring Data MongoDB repositories
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    banner-mode: off

logging:
  level:
    root: debug
