server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: 12345

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

  main:
    banner-mode: off


logging:
  level:
    root: debug

